# Base image
FROM python:3.11.4-slim

# Install dependencies
RUN pip install 'mlflow==1.30.0' \
                'mldesigner==0.1.0b4' \
                'azureml-core==1.47.0' \
                'azureml-dataprep==4.10.1' \
                'azureml-defaults==1.47.0' \
                'azure-ai-ml==1.4.0' \
                'azureml-mlflow==1.47.0' \
                'azure-identity==1.12.0' \
                'mltable==1.2.0' \
                'numpy==1.21.6' \
                'pandas==1.3.5' \
                'joblib==1.2.0' \
                'scikit-learn==1.0.2' \
                'scikit-optimize==0.9.0' \
                'lightgbm==3.3.5' \
                'protobuf==3.20.0' \
                'plotly-express==0.4.1' \
                'pyyaml==5.4.1' \
                'fire==0.4.0' 