# Base image
FROM mcr.microsoft.com/azureml/curated/sklearn-1.0:11

# Install dependencies
RUN pip install 'azure-ai-ml==1.4.0' \
                'azure-identity==1.14.0' \
                'numpy==1.25.2' \
                'lightgbm==3.3.5' \
                'protobuf==3.20.0' \
                'pyyaml==5.4.1' \
                'fire==0.5.0' 