# Base image
FROM python:3.11.4-slim

# Install dependencies
RUN pip install 'mldesigner==0.1.0b4'\
                'azureml-core==1.47.0'\
                'azureml-defaults==1.47.0'\
                'azure-identity==1.12.0'\
                'scikit-learn==1.0.2'\
                'protobuf==3.20.0'\
                'pyyaml==5.4.1'\
                'fire==0.4.0'