azure:
  subscription_id : 'XXXXXX'
  resource_group : 'XXXXXX'
  aml_workspace_name : 'XXXXXX'
model:
  name: 'iot_ckpt'
  version: '1'
endpoint:
  name: 'iot-weather-api'
  description: 'API to compute the risk of fire alarm.'
  auth_mode: 'key'
  traffic:
    blue: 100
    green: 0
deployment:
  name: 'blue' # blue or green
  instance_type: "Standard_DS1_v2"
  instance_count: 1
autoscale:
  name: 'iot_autoscale'
  capacity:
    minimum: 2
    maximum: 4
  threshold:
    cpu:
      increase: 70 # %
      decrease: 50 # %
      cooldown: 3600 # seconds
    latency:
      increase: 1000 # miliseconds
      decrease: None # miliseconds
      cooldown: 3600 # seconds