channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pandas~=1.3.0
- scipy~=1.10.0
- numpy~=1.22.0
- pip:
  - wheel~=0.38.1
  - azureml-core==1.52.0
  - azureml-defaults==1.52.0
  - azureml-mlflow==1.52.0
  - azureml-telemetry==1.52.0
  - azureml-automl-common-tools==1.52.0
  - scikit-learn~=1.0.0
  - joblib~=1.2.0
  # vulnerabilities
  - cryptography>=41.0.3
  - certifi >= 2023.07.22
  - requests >= 2.31.0
  # Job specific
  - azure-ai-ml==1.4.0
  - azure-identity==1.14.0
  - mltable==1.5.0
  - mlflow==2.6.0
  - lightgbm==3.3.5
  - protobuf==3.20.0
  - plotly-express==0.4.1
  - pyyaml==5.4.1
  - fire==0.4.0