channels:
- anaconda
- conda-forge
dependencies:
- python=3.8
- pip=21.3.1
- pip:
  - azure-ai-ml==1.4.0
  - azure-identity==1.14.0
  - mltable==1.5.0
  - mlflow==2.6.0
  - scikit-optimize==0.9.0
  - lightgbm==3.3.5
  - protobuf==3.20.0
  - plotly-express==0.4.1
  - pyyaml==5.4.1
  - fire==0.4.0