$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

# General information about the component
name: train_ml
display_name: Train ML
description: A template component to train a supervised learning ML model from a series of available models.
tags:
  author: Antonio Zarauz Moreno, CEO @MAIACorp
  version: "1"

# Inputs and outputs
inputs:
  input_path:
    type: uri_folder
    optional: false
  model_name:
    type: string
    optional: false
  experiment_name:
    type: string
    optional: false
  target_var:
    type: string
    optional: false
  n_calls:
    type: integer
    min: 20
    max: 200
    default: 100
    optional: true
  n_initial_points:
    type: integer
    min: 5
    max: 15
    default: 10
    optional: true
  seed:
    type: integer
    min: 1
    max: 9999
    default: 42
    optional: true
outputs:
  output_path:
    type: uri_folder

# The source code path of it's defined in the code section and when the
# component is run in cloud, all files from that path will be uploaded
# as the snapshot of this component
code: ./

# Environment takes care of source image and dependencies
# https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-environments-v2?view=azureml-api-2&tabs=cli
environment:
  image: train_ml_env:1

# Cluster instance
compute: azureml:cpu-cluster

# Distribution type
distribution:
  type: mpi
  process_count_per_instance: 1 # Number of nodes per instance

# How many VMs we need
resources:
  instance_count: 1 # Number of instances to create

# The command section specifies the command to execute while running
# this component
command: python ./main.py --input_path ${{inputs.input_path}} --model_name ${{inputs.model_name}} --experiment_name ${{inputs.experiment_name}} --target_var ${{inputs.target_var}} $[[--n_calls '${{inputs.n_calls}}']] $[[--n_initial_points '${{inputs.n_initial_points}}']] $[[--seed '${{inputs.seed}}']] --output_path ${{outputs.output_path}}