name: data_ckpt_conda_env
channels:
  - defaults
dependencies:
  - python=3.10.7
  - pip=23.2
  - pip:
    - mldesigner==0.1.0b11
    - azureml-core==1.47.0
    - azure-ai-ml==1.4.0
    - azureml-defaults==1.47.0
    - azure-identity==1.12.0
    - protobuf==3.20.0
    - pyyaml==5.4.1
    - fire==0.4.0