name: data_ckpt_conda_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pip=23.0.1
  - pip:
    - mldesigner==0.1.0b4
    - azureml-core==1.47.0
    - azureml-defaults==1.47.0
    - azure-identity==1.12.0
    - protobuf==3.20.0
    - pyyaml==5.4.1
    - fire==0.4.0